### ISSUE TITLE
Problem with npm install from package.json

### ISSUE THREAD

**Issue by Schwersenz-OGOIO** [sous-chefs/nodejs#113]
I want to provision a VM using vagrant and chef-solo.

I have a `package.json` file in a folder `/var/www`.
When I do this in my recipe 

```
nodejs_npm 'main' do
  path '/var/www'
  json true
end
```

I end up with this error:

```
==> default:       ================================================================================
==> default:       Error executing action `run` on resource 'execute[install NPM package main]'
==> default:       ================================================================================
==> default:
==> default:       Mixlib::ShellOut::ShellCommandFailed
==> default:       ------------------------------------
==> default:       Expected process to exit with [0], but received ''
==> default:       ---- Begin output of npm install   ----
==> default:       STDOUT:
==> default:       STDERR:
==> default:       ---- End output of npm install   ----
```

When I add every dependency from my `package.json` individually to my recipe like this 

```
nodejs_npm 'node-sass' do
  path '/var/www'
end
```

and so on, everything works fine. Also, when I don't do any npm installing in my recipe at all, and just do it manually afterwards, everything also works fine and I get an exit code 0.

npm: 3.5.2
node: 5.3.0

Any ideas?

**Comment by RShackleton** [comment]
+1 Also getting this error. Could it be due to installing a large number of dependencies?

**Comment by japel** [comment]
This could be a problem related to having to little memory on the vm.
I had a similar problem. After I told vagrant to modify the vm to have 1gb of ram it worked...

```ruby
config.vm.provider :virtualbox do |v|
  v.customize ["modifyvm", :id, "--memory", 1048]
end
```

**Comment by MarkGibbons** [comment]
When I have enough memory and disk space installing using package.json works. I'm going to recommend the previous solution and close this issue.
