### ISSUE TITLE
npm symlink missing

### ISSUE THREAD

**Issue by rmoriz** [sous-chefs/nodejs#119]
When node is installed using the binary method, it automatically creates a symlink `/usr/local/bin/npm` to the embedded npm.

However when using the `source` method to install npm, no symlink will be created and/or updated.

I'm not sure if this is caused by a change of the npm `Makefile` with recent versions or just an inconsistency of the cookbook.

**Comment by bubenshchykov** [comment]
+1

**Comment by Dreeg** [comment]
+1

**Comment by MarkGibbons** [comment]
The tests for the source install are chancy too.  Those tests should be repaired as part of fixing this issue.

**Comment by MarkGibbons** [comment]
Added test for /usr/local/bin/npm and /usr/local/bin/npx.  Initial testing of #222 shows those files exist.

**Comment by MarkGibbons** [comment]
The #222 shows the files are installed and available in /usr/local/bin during a source build
