### ISSUE TITLE
Install yarn?

### ISSUE THREAD

**Issue by ketan** [sous-chefs/nodejs#155]
... via an optional recipe `nodejs::yarn`

Is this something you'd rather see in a different cookbook?

**Comment by eagleeye** [comment]
you can install yarn with recipe npm_package, action :install

**Comment by ketan** [comment]
From the yarn install docs https://yarnpkg.com/en/docs/install#alternatives-tab

> Note: Installation via npm is generally not recommended. npm is non-deterministic, packages are not signed, and npm does not perform any integrity checks other than a basic SHA1 hash, which is a security risk when installing system-wide apps.
> 
> For these reasons, it is highly recommended that you install Yarn through the installation method best suited to your operating system.

**Comment by eagleeye** [comment]
@ketan as for me it's better to create new cookbook, different from nodejs

**Comment by aspyatkin** [comment]
@ketan I have written [this cookbook](https://github.com/aspyatkin/yarn-cookbook) for my projects, you can make use of it in order to install Yarn.

**Comment by MarkGibbons** [comment]
A separate yarn installation and yarn_package would be interesting features.
