### ISSUE TITLE
Error installing npm packages with node 8.5

### ISSUE THREAD

**Issue by markitosgv** [sous-chefs/nodejs#188]
### Cookbook version
master or 4.0, I'm tring with master branch but PR #177 seems not work

### Chef-client version
12

### Platform Details
Centos 6.9

### Scenario:
Installing/updating npm packages with node 8.5

### Steps to Reproduce:
Povisioning a vagrant machine with:

```json
"default_attributes": {
    "nodejs": {
      "install_method": "binary",
      "version": "8.5.0",
      "binary": {
        "checksum": "0000710235e04553147b9c18deadc7cefa4297d4dce190de94cc625d2cf6b9ba"
      },
      "npm_packages": [
        { "name": "gulp" },
        { "name": "yarn" },
        { "name": "phantomjs" }
      ]
    }
  }
```

### Expected Result:
install ok

### Actual Result:
Error executing action `run` on resource 'execute[install NPM package gulp]'
765: unexpected token at ''

**Comment by jeffbyrnes** [comment]
Node v8 is no longer maintained, closing this out.
