### ISSUE TITLE
Install does not wait for apt-get update to complete

### ISSUE THREAD

**Issue by jamime** [sous-chefs/nodejs#189]
### Cookbook version
4.0.0

### Chef-client version
13.4.19

### Platform Details
Ubuntu 16.04

### Scenario:
I'm trying to install the latest nodejs but the install occurs without the apt cache being updated with the new source.

```
Recipe: nodejs::repo
  * apt_package[apt-transport-https] action install (up to date)
  * apt_repository[node.js] action add
    * execute[install-key 1655a0ab68576280] action run (skipped due to not_if)
    * execute[apt-cache gencaches] action nothing (skipped due to action :nothing)
    * apt_update[node.js] action nothing (skipped due to action :nothing)
    * file[/etc/apt/sources.list.d/node.js.list] action create
      - update content in file /etc/apt/sources.list.d/node.js.list from e3b0c4 to 70a8ae
      --- /etc/apt/sources.list.d/node.js.list	2017-10-25 13:43:08.785437883 +0100
      +++ /etc/apt/sources.list.d/.chef-node20171025-12506-m5uvle.js.list	2017-10-25 13:44:54.100100127 +0100
      @@ -1 +1,2 @@
      +deb      "https://deb.nodesource.com/node_6.x" xenial main
    * execute[apt-cache gencaches] action run
      - execute apt-cache gencaches
    * apt_update[node.js] action update
      - force update new lists of packages
      * directory[/var/lib/apt/periodic] action create (up to date)
      * directory[/etc/apt/apt.conf.d] action create (up to date)
      * file[/etc/apt/apt.conf.d/15update-stamp] action create_if_missing (up to date)
      * execute[apt-get -q update] action run
        - execute apt-get -q update
    
  
Recipe: nodejs::nodejs_from_package
  * apt_package[nodejs] action install
    - install version 4.2.6~dfsg-1ubuntu4.1 of package nodejs

```

### Steps to Reproduce:
`include_recipe 'nodejs'`

### Expected Result:
I expect the apt_update to finish and `$ sudo apt-cache policy nodejs` to return the following
```
nodejs:
  Installed: (none)
  Candidate: 6.11.5-1nodesource1
  Version table:
     6.11.5-1nodesource1 500
        500 https://deb.nodesource.com/node_6.x xenial/main amd64 Packages
     4.2.6~dfsg-1ubuntu4.1 500
        500 http://gb.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
     4.2.6~dfsg-1ubuntu4 500
        500 http://gb.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
```

When the install is performed I expect it to come from nodesource.

### Actual Result:
The install happens but the `apt-cache policy` does not include nodesource so the wrong version is installed.
```
nodejs:
  Installed: (none)
  Candidate: 4.2.6~dfsg-1ubuntu4.1
  Version table:
     4.2.6~dfsg-1ubuntu4.1 500
        500 http://gb.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
     4.2.6~dfsg-1ubuntu4 500
        500 http://gb.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
```

To fix this I had to run `sudo apt-get update` manually then re-run the cookbook.

**Comment by MarkGibbons** [comment]
Need to try to reproduce the error.

**Comment by thirumoorthir** [comment]
Hi i used this cookbook to converge ubuntu-1604  with chef version 16.6.14 and i get below result,
`agrant@default-ubuntu-1604:~$ sudo apt-cache policy nodejs
nodejs:
  Installed: 10.23.0-1nodesource1
  Candidate: 10.23.0-1nodesource1
  Version table:
 *** 10.23.0-1nodesource1 500
        500 https://deb.nodesource.com/node_10.x xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     4.2.6~dfsg-1ubuntu4.2 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages
     4.2.6~dfsg-1ubuntu4 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages`

@MarkGibbons  i think we can close this as it is working as expected
