### ISSUE TITLE
i am install nodejs 8.11.4 but it shows v6.16.0

### ISSUE THREAD

**Issue by ghost** [sous-chefs/nodejs#198]
### Cookbook version
[Version of the cookbook where you are encountering the issue]

### Chef-client version
[Version of chef-client in your environment]

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]

### Scenario:
[What you are trying to achieve and you can't?]

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by nareshabbanapuri** [comment]
in attribute
node.default['nodejs']['install_method'] = 'binary'
node.default['nodejs']['version'] = '8.11.4'
when i run nodejs --version the result is v6.16.0 
how it comes and what's solution for this

**Comment by nareshabbanapuri** [comment]
error getting like this 
 FATAL: Chef::Exceptions::MultipleFailures: Multiple failures occurred:
       * Chef::Exceptions::ChecksumMismatch occurred in chef run: remote_file[/tmp/kitchen/cache/nodejs-binary-8.11.0.tar.gz] (/tmp/kitchen/cache/cookbooks/ark/resources/default.rb line 62) had an error: Chef::Exceptions::ChecksumMismatch: Checksum on resource (3df19b) does not match checksum on content (93ab3e)
       * Mixlib::ShellOut::ShellCommandFailed occurred in delayed notification: execute[unpack /tmp/kitchen/cache/nodejs-binary-8.11.0.tar.gz] (/tmp/kitchen/cache/cookbooks/ark/resources/default.rb line 72) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
       ---- Begin output of /bin/tar xzf /tmp/kitchen/cache/nodejs-binary-8.11.0.tar.gz --strip-components=1 ----
       STDOUT:
       STDERR: tar (child): /tmp/kitchen/cache/nodejs-binary-8.11.0.tar.gz: Cannot open: No such file or directory
       tar (child): Error is not recoverable: exiting now
       /bin/tar: Child returned status 2
       /bin/tar: Error is not recoverable: exiting now
       ---- End output of /bin/tar xzf /tmp/kitchen/cache/nodejs-binary-8.11.0.tar.gz --strip-components=1 ----
       Ran /bin/tar xzf /tmp/kitchen/cache/nodejs-binary-8.11.0.tar.gz --strip-components=1 returned 2

**Comment by nareshabbanapuri** [comment]
kk done

**Comment by MarkGibbons** [comment]
This looks like 3 different bug reports and the details are really unclear.  Check to see if any of the issues can be reproduced.
