### ISSUE TITLE
npm_package NoMethodError

### ISSUE THREAD

**Issue by Daz762** [sous-chefs/nodejs#206]
### Cookbook version
6.0.0

### Chef-client version
16.2.73

### Platform Details
Mac OS 10.14

### Scenario:
When the cookbook compiles I get the following NoMethodError:

undefined method `npm_package' for cookbook: nodejs, recipe: npm_packages :Chef::Recipe

### Steps to Reproduce:
Added nodejs cookbook as dependency in metadata.rb:

depends 'nodejs'

added include_recipe 'nodejs' to default.rb

Cookbook fails to compile with the error described in ###Scenario

### Expected Result:
Successful cookbook compile

### Actual Result:
Cookbook fails to compile with NoMethodError

**Comment by MarkGibbons** [comment]
thanks for the report of the problem.
This issue should be fixed in version 7.0.1 of nodejs.  Newer versions of check required changes to the custom resources. The provides statement was added.
