### ISSUE TITLE
yum https repository error [Errno 14] curl#35 "TCP connection reset by peer"

### ISSUE THREAD

**Issue by pmandha23** [sous-chefs/nodejs#207]
### Cookbook version
version '7.0.1'

### Chef-client version
Chef: 13.12.14

### Platform Details
CentOS Linux release 7.8.2003 (Core)

### Scenario:
RunningChef-Client

### Steps to Reproduce:
First Chef-client Run

### Expected Result:
Need to configure and install NodeJs Package on CentOS

### Actual Result:
execute[yum-makecache-node.js] (/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.12.14/lib/chef/provider/yum_repository.rb line 60) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of yum -q -y makecache --disablerepo=* --enablerepo=node.js ----
    STDOUT: 
    STDERR: https://rpm.nodesource.com/pub_10.x/el/7/x86_64/repodata/repomd.xml: [Errno 14] curl#35 - "TCP connection reset by peer"
    Trying other mirror.

**Comment by MarkGibbons** [comment]
I can't reproduce this error.
