### ISSUE TITLE
Add platforms centos7, opensuse and fedora to the ci/cd pipeline.

### ISSUE THREAD

**Issue by MarkGibbons** [sous-chefs/nodejs#218]
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## :person_frowning: Problem Statement

The builds for centos7, opensuse and fedora dokken images failed.  Fix them and get them added back to the ci/cd builds and tests.

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by MarkGibbons** [comment]
Notes about centos 7, it fails to build from source.
It looks like this is due to the fact that the default compiler on EL7 isn't new enough to compile it correctly as noted here: nxhack/openwrt-node-packages#470

A possible workaround would be to use the devtoolkit package from SCL, but that's probably better done in a separate PR using the yum-centos cookbook to enable the repository.

**Comment by zhmurko** [comment]
hi @MarkGibbons 
i would like to prepare a PR for this issue. Please assign it to me

**Comment by MarkGibbons** [comment]
You've got it.   Centos 7 runs everything except source installs at this point.  Good luck.
