### ISSUE TITLE
Add idempotent LWRP for 'npm link'

### ISSUE THREAD

**Issue by rhass-r7** [sous-chefs/nodejs#41]
It would be nice to have support for 'npm link' to manage linking a given version of an application to a specific location on disk. Additionally, adding this as a 'link' attribute to the existing nodejs_npm LWRP would be extremely useful.

**Comment by MarkGibbons** [comment]
Given the age of the PR I'm going to close this. I also don't see anything clear enough to implement.
@rhass-r7  thanks for the ideas.
