### ISSUE TITLE
Check to see if package installed should take into account user

### ISSUE THREAD

**Issue by jfbibeau** [sous-chefs/nodejs#50]
I ran into a funny problem where npm always tried to install the package. After a bit of troubleshooting, I found out it was because the npm list command didn't run as the same user as the npm install command. This breaks when you have a prefix set.

For example, if I run "npm install -global <package>" as the vagrant user, and my npmrc contains a prefix of ~/npm, it'll put the package there.

However on the next converge, it'll run "npm list -global -json" as the root user, so it won't find the package.

The resource.user param should be passed into the shell that executes npm list...

**Comment by MarkGibbons** [comment]
Needs a review to determine if this report is still an issue. Also review the suggest fix.  A fix may already have been merged.

**Comment by MarkGibbons** [comment]
Adding user to the command without setting the path gets an error complaining about root owned files in the cache.  I'm not able to reproduce an issue in a meaningful way. Closing due to age and lack of a way to reproduce.
@jfbibeau thank you for the report.
